### ISSUE TITLE
Microsoft.Graph.ServiceException in UWP app

### ISSUE THREAD

**Issue by tipa** [OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#3] opened 2016-08-16 22:49 UTC
I am trying to authenticate in a UWP app via the following code (app-id X'd out):
```
var authProvider = new MsaAuthenticationProvider("00000000XXXXXXXX", null, new string[] { "onedrive.appfolder" });
await authProvider.AuthenticateUserAsync();
```
Unfortunately, the UI to authenticate doesnt appear, instead a ServiceException is raised in `AuthenticateUserAsync` (Code: authenticationCancelled)

**Comment by tipa** [comment] 2016-08-18 07:23
Somehow, it works now...

**Comment by tipa** [comment] 2016-08-18 08:02
I was wrong... `AuthenticateUserAsync` works, when the user already gave the app the permission (with a previous OneDrive SDK version). `AuthenticateUserAsync `still throws an exception when the user did not authorize the app the access OneDrive yet and the popup should be shown. Tested on mobile & desktop both having the Anniversary Update.

**Comment by j-0** [comment] 2016-08-18 13:47
I ran into the same issue (Tested on Desktop w/o Anniversary Update) when calling AuthenticateUserAsync. No UI is shown, the exception with Code authenticationCancelled is thrown immediatly. Before updating the OneDrive-SDK Nuget everything worked fine (so no error on app registration part)

**Comment by cdmayer** [comment] 2016-08-24 18:12
You must pass in a `returnUrl`. It must be equal to the value you set up in the App settings.

In the future, you can debug more easily by cloning the auth-adapter code and building a debug binary for use while developing your app. Check out the repo here: https://github.com/OneDrive/onedrive-sample-photobrowser-uwp

**Comment by tipa** [comment] 2016-08-24 19:45
Looking at the code, when I pass null as `returnUrl`, it will be replaced by the ApplicationUrl of the app automatically: https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/blob/21aa5d4354adfc080f9b55b9ca446dfa4205adc4/src/OneDrive.Sdk.Authentication.Common/MsaAuthenticationProvider.cs#L84-L86

Where can I set a ApplicationUrl manually then? Can I find the app settings you are talking about here: https://apps.dev.microsoft.com/#/application/sapi/00000000XXXXXXX? Because under the chapter "mobile application" there is no field I can manually set a value.

**Comment by cdmayer** [comment] 2016-08-24 22:56
I see the issue you are having. You are correct that later the `returnUrl` gets set, however, this gets set to a local URL that doesn't work with the MSA auth flow. I will investigate that separately. Until then, you should be able to get unblocked:

- Go to your app's page (that you linked to above)
- Under **Platforms** you should have _Mobile Application_ with 2 values of redirect URI, one local and one remote. Do you not have both?
- Pass the remote URI (something like https://login.live.com/oauth20_desktop.srf) into the constructor of the `MsaAuthenticationProvider`

That works locally for me (and I am able to repro your issue locally, too). Please let me know if you get stuck anywhere. If you don't have a remote URI, please paste a screen clipping of what you see (not the whole page, just the _Mobile Application_ section).

**Comment by tipa** [comment] 2016-08-24 23:48
As I said in my previous comment I already tried the remote URI without success. Below you find the screen I see in the app settings as well as the code that is not working.

![2](https://cloud.githubusercontent.com/assets/2863198/17951848/ca3f8c3e-6a65-11e6-8b08-39aefff39fe4.PNG)
![unbenannt](https://cloud.githubusercontent.com/assets/2863198/17951850/cd075bae-6a65-11e6-80a7-9d31900e038a.PNG)

**Comment by ericpapamarcos** [comment] 2016-08-26 01:29
I'm seeing the same issue. I'm using the same `MsaAuthenticationProvider` constructor as tipa except I have an additional scope (offline_access).

I have a UWP app (14393 SDK) with a button. Clicking the button fires an event handler, which in turns calls the `MsaAuthenticationProvider` constructor and `AuthenticateAsync`.

In my testing I found that the authenticationCancelled exception disappears if the code is not called from an event handler (ex: `RoutedEventArgs`). For example, if I temporarily call the code from the `OnNavigatedTo` method, I don't get the exception and the sign in dialog appears.

Is it possible that `MsaAuthenticationProvider` is not cooperating with event handlers?

**Comment by cdmayer** [comment] 2016-08-26 20:18
@tipa Can you post more of the code you're using? I was not able to reproduce the issue you're having.

**Comment by AK-47ru** [comment] 2016-08-27 12:01
I found another way to reproduce the exception any time. 
You can reproduce the error in the https://github.com/OneDrive/onedrive-sample-photobrowser-uwp.

After you press "Login as MSA" and got the Sign In window, closed it without signing. 
The next time you press login button you'll get the error without the login window appears again. 

Just modify the code that is would not navigate to MainPage if not signed in and the program stay on AccountSelection page for another try.

**Comment by mhomde** [comment] 2016-08-28 04:09
I think I'm having the same problem. It seems to be working on an off locally but failing in release mode. Here's a stack trace¨


   at Microsoft.OneDrive.Sdk.Authentication.WebAuthenticationBrokerWebAuthenticationUi.<AuthenticateAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 128
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 497
   at Microsoft.OneDrive.Sdk.Authentication.OAuthHelper.<GetAuthorizationCodeAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 128
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 497
   at Microsoft.OneDrive.Sdk.Authentication.MsaAuthenticationProvider.<AuthenticateUserAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs:line 61
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 187
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 156
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 128
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult() in f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs:line 410
   at Microsoft.OneDrive.Sdk.Authentication.MsaAuthenticationProvider.<AuthenticateUserAsync>d__22.MoveNext()

**Comment by edandersen** [comment] 2016-08-29 12:14
+1. This is blocking updating to 2.0.0.

**Comment by tipa** [comment] 2016-09-05 20:02
Any updates on this or any ways I can help? This is blocking me updating my app as well.

**Comment by tenevincent** [comment] 2016-09-07 14:19
I have the same problem with this api, when trying to debug locally, but when deploying in the mobile emulator it work. I move all the API in a portable assembly outside the UI main assembly.

Have anyone an idea?

**Comment by cdmayer** [comment] 2016-09-07 15:50
Still working on this. Will report back when I have updates.

**Comment by cdmayer** [comment] 2016-09-07 23:00
New binaries are signed and uploaded to [NuGet](https://www.nuget.org/packages/Microsoft.OneDriveSDK.Authentication/1.0.2). Please try installing 1.0.2 of the Auth Adapter and let me know if it fixes your issue.

**Comment by d32f123** [comment] 2016-09-08 00:26
Still does not seem to work for me. Doing the same thing as @ericpapamarcos is doing.

**Comment by cdmayer** [comment] 2016-09-08 00:43
I am not able to repro that issue. Can you try adding the following to your event handler (you'll need to make some adjustments based on your actual implementation details):

```csharp

            try
            {
                result = await authUi.AuthenticateAsync(requestUri, callbackUri);
            }
            catch (ServiceException ex)
            {
                var message = ex.Error.Code + ": " + ex.Error.Message;
                throw;
            }
```

Then insert a break point at the `throw` statement and tell me what the value of `message` is? That will help diagnose the issue.

**Comment by d32f123** [comment] 2016-09-08 00:52
The value of message is: "authenticationFailure: "
It does work, if I insert the code into a WPF application for example, though.

**Comment by tipa** [comment] 2016-09-08 05:53
I cannot even update to the Nuget version 1.0.2 - "Package restore failed"

**Comment by d32f123** [comment] 2016-09-08 06:38
Well, I've reinstalled Visual Studio with all the newest updates... and for some reason it is all working for me now. Oh, and @tipa, I'm unable to update to 1.0.2 as well, but it works fine after reinstalling with 1.0.1.

**Comment by tipa** [comment] 2016-09-08 08:28
I reinstalled the 1.0.1 package, did a full rebuild but still same error

**Comment by cdmayer** [comment] 2016-09-08 14:36
If you are not getting a value in `ex.Error.Message` then you are still running the old version of the package. You need to double-check that you are on 1.0.2.

**Comment by tipa** [comment] 2016-09-08 14:47
As I already stated above, I cannot update to version 1.0.2 on my UWP project. Following error pops up: 

```
Restoring packages for ...\project.json...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.clients.activedirectory/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.clients.activedirectory/index.json 459ms
Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0). Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0.
Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm. Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm).
Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-arm-aot. Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64. Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64).
Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x64-aot. Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86. Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86).
Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 is not compatible with uap10.0 (UAP,Version=v10.0) / win10-x86-aot. Package Microsoft.IdentityModel.Clients.ActiveDirectory 1.0.0 supports: net40 (.NETFramework,Version=v4.0)
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).
Package restore failed for 'MyApp'.
Package restore failed. Rolling back package changes for 'MyApp'.
========== Finished ==========
Time Elapsed: 00:00:02.5641889
```

**Comment by cdmayer** [comment] 2016-09-08 14:50
@tipa You have pointed out a different issue, thank you for doing so. The .nuspec file does not have the correct package version constraints. Try first upgrading `Microsoft.IdentityModel.Clients.ActiveDirectory` to a newer version, such as 2.28. It must be >2.21 and <3.0. Then, install 1.0.2 of this package. In the meantime I need to update the package requirements.

**Comment by cdmayer** [comment] 2016-09-08 14:56
Updated to 1.0.3. Same binaries, updated package requirements.

**Comment by cdmayer** [comment] 2016-09-08 15:01
@tipa please let me know if you are still having issues with 1.0.3. I would not expect you to be getting quite the same errors with that version.

**Comment by tipa** [comment] 2016-09-08 15:01
I can update it now but the issue is still not solved for me. Now the error message is the following:

`The provided value for the input parameter 'redirect_uri' is not valid. The client application must be marked as 'mobile', or the value must be an absolute URL which matches the registered redirect URI.`

No matter if I use 
`var authProvider = new MsaAuthenticationProvider("00000000XXXXX", null, new string[] { "onedrive.readonly" });`
or
`var authProvider = new MsaAuthenticationProvider("00000000XXXXX", "https://login.live.com/oauth20_desktop.srf", new string[] { "onedrive.readonly" });`

**Comment by cdmayer** [comment] 2016-09-08 15:54
@tipa the good news is that the error message you're getting means that we have solved the `authenticationCancelled` problem! Hooray!

Usually the error message you're getting is caused by application settings not matching the inputs you provide. Can you double-check that you have the correct ApplicationId set? If that still doesn't work, I think we need to check and see if the issue truly lies in the SDK or not. Try logging in using a web request tool like [Fiddler](https://www.telerik.com/download/fiddler) and the [instructions here](https://dev.onedrive.com/auth/msa_oauth.htm#code-flow).

**Closed** 2016-09-08 15:59 UTC

**Comment by tipa** [comment] 2016-09-08 17:01
It is working now, thanks for your patience!

**Comment by cdmayer** [comment] 2016-09-08 17:02
@tipa glad we got it solved :100:

**Comment by tenevincent** [comment] 2016-09-09 06:16
I have updated the assembly "Microsoft.OneDrive.Sdk.Authentication" to 1.0.3 and it is working now,

thank you for the update!

**Comment by AK-47ru** [comment] 2016-09-10 02:01
Works like a charm on 1.0.3,
many thanks.
